### ISSUE TITLE
draft docs

### ISSUE THREAD

**Issue by tim-hm** [glimpse-protocol/docs#1]
To start lets focus primarily on content and we can make things look nicer down the line. 

Lets start a new docs repo for this as well which we can eventually make public.

As a first iteration these are the bits I'm keen on seeing (focus on guides and reference i can take care of intro):

## Introduction

- general overview of how it works
- benefits (ie [performance](https://github.com/glimpse-protocol/zerojs/issues/11), carbon, etc).

## Guides

1. Example integration
2. GAM setup

## Reference

1. window.zjs api

**Comment by eddyu0** [comment]
is the GAM setup through our UI or the publisher's own GAM server?

**Comment by tim-hm** [comment]
Through their gam account. Essentially we just need to show how they should setup their 100% sponsorship line item (ie so they put the correct custom key value on it)
